# Generated by Django 2.2.4 on 2019-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190912_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dvdID',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='users_ID',
            field=models.CharField(max_length=250),
        ),
    ]
